### ISSUE TITLE
Unclosed Resource Warnings

### ISSUE THREAD

**Issue by sfneal** [sfneal/pdfconduit#2]
Running test_flatten.py yields a number of UnclosedResource warnings.  Using the pdfrw method instead of pypdf3 during Merge call in Flatten seemed to limit the number of warnings but not eliminate them.  PyPDF3 appears to be the origin of the problem.

**Comment by mrstephenneal** [comment]
It appears that the source of UnclosedResource warnings has been fixed based on MacOS tests.  Not sure what was changed that resulted in the fix.  Has not been tested on Windows 10 (Windows 10 was raising more errors than MacOS).

**Comment by mrstephenneal** [comment]
Windows 10 test_flatten.py console output

Launching unittests with arguments python -m unittest C:/Users/Stephen/Scripts/pdfconduit/tests/test_flatten.py in C:\Users\Stephen\Scripts\pdfconduit\tests
ResourceWarning: unclosed file <_io.BufferedRandom name=3> [flatten.py:94]
ResourceWarning: unclosed file <_io.BufferedRandom name=3> [pdf.py:54]
flatten 1x      --> 2.527738332748413
flatten 2x      --> 5.085687160491943
flatten 3x      --> 9.904916048049927


Ran 3 tests in 17.690s

OK

**Comment by mrstephenneal** [comment]
Unclosed resource warnings have completely disappeared from macOS tests.  Testings Windows 10 now

**Comment by mrstephenneal** [comment]
Flatten module still causing unclosed file warnings to be raised.

C:/Users/Stephen/Scripts/pdfconduit/tests\test_flatten.py
ResourceWarning: unclosed file <_io.BufferedRandom name=3> [pdf2img.py:81]
ResourceWarning: unclosed file <_io.BufferedRandom name=3> [pdf.py:55]
tests test_flatten TestFlatten test_flatten_1x --> 31.5
